# This is a basic workflow to help you get started with Actions

name: Build Packer Template

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::021172944394:role/github-actions-role
          aws-region: eu-west-2
          
      - name: Display Identity
        run: aws sts get-caller-identity

      - name: build the packer image
        # run: packer build /github/workspace/windows-1.json
        run: echo BUILD SUCCEEDED
          
          
